import { SEOHead } from "@/components/seo/SEOHead";
import { APP_NAME } from "@/config/seo";

const TermsOfUse = () => {
  return (
    <>
      <SEOHead
        title={`Terms of Use - ${APP_NAME}`}
        description={`Read ${APP_NAME}'s Terms of Use to understand the rules and guidelines for using our platform.`}
        url="/terms-of-use"
        canonical="/terms-of-use"
      />
      <div className="terms-of-use p-6 max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-4">Terms of Use</h1>
        <p>Last Updated: November 9, 2024</p>

        <p className="mt-6">
          Please read these Terms of Use ("Terms", "Terms of Use") carefully
          before using {APP_NAME} (the "Service") operated by Khaled Hossain
          ("us", "we", "our", "me", "biggest daddy", or "I"). Your access to and
          use of the Service is conditioned on your acceptance of and compliance
          with these Terms. These Terms apply to all visitors, users, and others
          who access or use the Service.
        </p>

        <p className="mt-4">
          By accessing or using the Service, you agree to be bound by these
          Terms. If you disagree with any part of the terms, then you may not
          access the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Purpose and Limitations of the Service
        </h2>
        <p>
          The Service is designed to generate full business plans based on user
          input, leveraging different APIs. The content provided by the Service
          is intended for educational purposes only and should not be considered
          professional business advice. Users should consult with a professional
          advisor before making any decisions based on the content generated by
          the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Ownership of Data and Intellectual Property
        </h2>
        <p>
          All data submitted by users, including but not limited to email
          addresses and stories created, remains the property of the respective
          users. While we do not claim ownership rights over user-submitted
          data, by using our service, you grant us the right to use this data
          for purposes we deem relevant, including but not limited to marketing,
          analysis, service improvement, or any other operational purpose.
          Please note that data may become inaccessible or be removed from our
          systems at any time
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Data Privacy and Usage
        </h2>
        <p>
          We will store user data, including email addresses, stories, plots,
          posts, characters, places, and all other content created on the
          website, to enhance and optimize our service. While we prioritize
          internal use, we reserve the right to utilize this data for additional
          purposes aligned with our business goals, which may include analysis,
          research, and marketing. User data will not be shared, sold, or
          distributed to third parties outside of purposes that support the
          functionality and improvement of our service
        </p>
        <p>
          By using the Service, you agree that we may add your email address to
          our mailing list to notify you of new programs or updates related to
          our Service. You may unsubscribe from these communications at any
          time.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Disclaimer of Warranties
        </h2>
        <p>
          The Service is provided on an "as is" and "as available" basis. We
          make no warranties, express or implied, regarding the accuracy,
          reliability, or completeness of the content generated by the Service,
          and expressly disclaim any warranties of merchantability, fitness for
          a particular purpose, or non-infringement.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Limitation of Liability
        </h2>
        <p>
          In no event shall Khaled Hossain, {APP_NAME}, employees, or affiliates
          be liable for any indirect, incidental, special, consequential, or
          punitive damages, including but not limited to loss of profits, data,
          or use, whether in an action in contract, tort (including but not
          limited to negligence), or otherwise, arising out of or in connection
          with your access to or use of the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">
          Changes to Terms of Use
        </h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace
          these Terms at any time. By continuing to access or use our Service
          after those revisions become effective, you agree to be bound by the
          revised terms. If you do not agree to the new terms, please stop using
          the Service.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the
          laws of the United States of America, without regard to its conflict
          of law provisions.
        </p>

        <h2 className="text-2xl font-semibold mt-6 mb-3">Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at{" "}
          <a
            href="mailto:khaledhossain.dev@gmail.com"
            className="text-blue-600 underline"
          >
            khaledhossain.dev@gmail.com{" "}
          </a>
          .
        </p>
      </div>
    </>
  );
};

export default TermsOfUse;
